# Generated by Django 5.2.9 on 2026-02-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
    ]
